temporarily disable schema GH action

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -26,44 +26,44 @@ permissions:
   contents: read
 
 jobs:
-  schema:
-    outputs:
-      invalid: ${{ steps.check-schema.outputs.invalid }}
-      schema: ${{ steps.check-schema.outputs.schema }}
-    runs-on: ubuntu-latest
-    concurrency:
-      group: schema-${{ github.ref }}
-      cancel-in-progress: true
-    steps:
-      - uses: actions/checkout@v3
-      - name: Download latest info.json schema
-        run: |
-          curl -sSL https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/master/apps/prairielearn/src/schemas/schemas/infoQuestion.json > latestSchema.json
-      - name: Check schema
-        id: check-schema
-        run: |
-          echo "schema=latestSchema.json" >> "$GITHUB_OUTPUT"
-          diff latestSchema.json tests/infoSchema.json
-          if [ $? -eq 0 ]; then
-            echo "invalid=false" >> "$GITHUB_OUTPUT"
-            exit 0
-          else
-            echo "invalid=true" >> "$GITHUB_OUTPUT"
-            exit 0
-          fi
-      - name: Comment if out of date
-        if: ${{ steps.check-schema.outputs.invalid == 'true' }}
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            core.warning(
-              "The info.json schema is out of date. Please update it to match the latest schema from PrairieLearn.",
-              {
-                title: "Schema out of date",
-                file: "tests/infoSchema.json",
-              }
-            );
+#   schema:
+#     outputs:
+#       invalid: ${{ steps.check-schema.outputs.invalid }}
+#       schema: ${{ steps.check-schema.outputs.schema }}
+#     runs-on: ubuntu-latest
+#     concurrency:
+#       group: schema-${{ github.ref }}
+#       cancel-in-progress: true
+#     steps:
+#       - uses: actions/checkout@v3
+#       - name: Download latest info.json schema
+#         run: |
+#           curl -sSL https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/master/apps/prairielearn/src/schemas/schemas/infoQuestion.json > latestSchema.json
+#       - name: Check schema
+#         id: check-schema
+#         run: |
+#           echo "schema=latestSchema.json" >> "$GITHUB_OUTPUT"
+#           diff latestSchema.json tests/infoSchema.json
+#           if [ $? -eq 0 ]; then
+#             echo "invalid=false" >> "$GITHUB_OUTPUT"
+#             exit 0
+#           else
+#             echo "invalid=true" >> "$GITHUB_OUTPUT"
+#             exit 0
+#           fi
+#       - name: Comment if out of date
+#         if: ${{ steps.check-schema.outputs.invalid == 'true' }}
+#         uses: actions/github-script@v6
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             core.warning(
+#               "The info.json schema is out of date. Please update it to match the latest schema from PrairieLearn.",
+#               {
+#                 title: "Schema out of date",
+#                 file: "tests/infoSchema.json",
+#               }
+#             );
 
 
   tests:
